name: Get UN M49 Region Codes Data

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 1 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Set up Python 3.9
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Generate data
        run: |
          python scraper.py
        env:
          GITHUB_PAGES: TRUE
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
